services:

  db:
    volumes:
          - db_data_test:/var/lib/postgresql/data
    env_file: envs/test.env

  auth:
    env_file: envs/test.env

  functional_tests:
    build:
      context: ..
      dockerfile: docker/dockerfiles/TestDockerfile
    depends_on:
      auth:
        condition: service_started
    env_file: envs/test.env
    volumes:
      - ../tests/functional:/tests/functional:ro
      - ../tests/test_result:/tests/result
    entrypoint: >
      sh -c "pytest functional/. -v --html=result/report.html --self-contained-html > result/tests_result.txt"


volumes:
  db_data_test:
